#!/usr/bin/env python3
"""
Compare an EbsdLib-emitted pole-figure-positions CSV against the committed
MTEX golden CSV bucket-by-bucket. Each bucket = (orient_id,
rotation_point_group, plane_family).

For each bucket, performs a greedy nearest-neighbor match between the EbsdLib
points and the MTEX points. Reports the max distance per bucket so problem
buckets sort to the top.

This script is a developer / diagnostic tool. The same comparison is performed
in-process by PoleFigurePositionTest.cpp at test time, so day-to-day CI does
not need this script. Use it when investigating a regression to inspect the
exact points and per-bucket worst-case distances.

Usage:
    python3 compare_pf_positions.py <ebsdlib_csv> <mtex_csv> [--tol 1e-3]

The MTEX golden lives next to this script
(Data/Pole_Figure_Validation/mtex_pole_figure_positions.csv) and is
regenerated by run_mtex_pole_figure_positions.sh in this same directory.
The EbsdLib CSV is produced by PoleFigurePositionTest at
<build>/Testing/Temporary/PoleFigurePositions/ebsdlib_pole_figure_positions.csv.
"""
import argparse
import csv
import math
import os
import sys
from collections import defaultdict


def canonicalize_equator(x, y, equator_eps=1e-5):
    """Stereographic projection of upper-hemisphere unit vectors lands inside
    the unit disk; equator points (z=0) land on the boundary circle. The
    `if z < 0 ... flip` rule used by both EbsdLib and MTEX is FP-unstable
    at z = 0, so antipodal pairs (+v, -v) on the equator can land at either
    (x, y) or (-x, -y) depending on which side of zero a rounding error
    lands. Both representations refer to the same crystallographic direction.

    To make the comparison stable, fold equator points (r >= 1 - eps) to a
    canonical antipode: prefer y > 0; ties broken by x > 0. Interior points
    are untouched."""
    r2 = x * x + y * y
    if r2 < (1.0 - equator_eps) ** 2:
        return x, y
    if y < -equator_eps:
        return -x, -y
    if abs(y) < equator_eps and x < 0.0:
        return -x, -y
    return x, y


def load_csv(path):
    buckets = defaultdict(list)
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            key = (int(row["orient_id"]), row["rotation_point_group"], row["plane_family"])
            x, y = canonicalize_equator(float(row["x"]), float(row["y"]))
            buckets[key].append((x, y))
    return buckets


def greedy_match_max_distance(a_pts, b_pts):
    """Greedy nearest-neighbor: for each point in `a_pts` find nearest unused
    in `b_pts`, return the maximum matched distance. If lengths differ, returns
    +inf (the prior count check should have caught that, but be safe)."""
    if len(a_pts) != len(b_pts):
        return math.inf, None
    used = [False] * len(b_pts)
    worst = 0.0
    worst_pair = None
    for ax, ay in a_pts:
        best_d = math.inf
        best_j = -1
        for j, (bx, by) in enumerate(b_pts):
            if used[j]:
                continue
            d = math.hypot(ax - bx, ay - by)
            if d < best_d:
                best_d = d
                best_j = j
        used[best_j] = True
        if best_d > worst:
            worst = best_d
            worst_pair = ((ax, ay), b_pts[best_j])
    return worst, worst_pair


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ebsdlib_csv", help="EbsdLib-emitted CSV (typically <build>/Testing/Temporary/PoleFigurePositions/ebsdlib_pole_figure_positions.csv)")
    ap.add_argument("mtex_csv", help="MTEX golden CSV (typically Data/Pole_Figure_Validation/mtex_pole_figure_positions.csv)")
    ap.add_argument("--tol", type=float, default=1e-3, help="Per-bucket max-distance tolerance (default 1e-3)")
    ap.add_argument("--top", type=int, default=20, help="Show top-N worst buckets (default 20)")
    args = ap.parse_args()

    for p in (args.ebsdlib_csv, args.mtex_csv):
        if not os.path.isfile(p):
            print(f"missing CSV: {p}", file=sys.stderr)
            return 1

    eb = load_csv(args.ebsdlib_csv)
    mt = load_csv(args.mtex_csv)

    eb_keys = set(eb.keys())
    mt_keys = set(mt.keys())
    only_eb = eb_keys - mt_keys
    only_mt = mt_keys - eb_keys
    common = sorted(eb_keys & mt_keys)

    if only_eb or only_mt:
        print(f"BUCKET KEY MISMATCH: only-in-EbsdLib={len(only_eb)}, only-in-MTEX={len(only_mt)}")
        for k in sorted(only_eb)[:5]:
            print(f"  only EbsdLib: {k}")
        for k in sorted(only_mt)[:5]:
            print(f"  only MTEX:    {k}")

    results = []
    for key in common:
        worst, pair = greedy_match_max_distance(eb[key], mt[key])
        results.append((worst, key, pair, len(eb[key])))

    results.sort(key=lambda r: -r[0])

    fail = sum(1 for w, *_ in results if w > args.tol)
    npass = len(results) - fail
    print(f"Buckets: {len(results)} compared, {npass} within tol={args.tol}, {fail} over tol")
    print()
    print("Top-{} worst buckets (max greedy-NN distance per bucket):".format(args.top))
    print(f"{'orient_id':>10} {'rpg':>6} {'family':<14} {'pts':>4} {'max_d':>14}  {'pair (eb -> mt)':<60}")
    for worst, key, pair, n in results[: args.top]:
        oid, rpg, fam = key
        if pair is None:
            pair_str = "(count mismatch)"
        else:
            (ex, ey), (mx, my) = pair
            pair_str = f"({ex:+.5f}, {ey:+.5f}) -> ({mx:+.5f}, {my:+.5f})"
        print(f"{oid:>10} {rpg:>6} {fam:<14} {n:>4} {worst:>14.2e}  {pair_str:<60}")

    return 0 if fail == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
